# PlayerLauncher v1.4.3
# View a sample configuration file and setup instructions at 
# https://github.com/AoHRuthless/PlayerLauncher/wiki/Config.yml
# PlayerLauncher can be downloaded at http://dev.bukkit.org/bukkit-plugins/playerlauncher/

Launch:
  Enabled: true
  Message: '&dYou have been launched. Sayonara!'
  Requirement:
    Amount: 1
    Item: diamond
  Remove-Required-Items-After-Launch: true
  Delay: 5
  Power: 8
  Launch-Pad: Sponge
  Explosions:
    Enabled: true
    Amount: 5
    Power: 4