# +---------------------------------------------------------------------------------------------+ #
#
# Configuration file for PlayerLauncher.
# View a sample configuration file and more detailed setup instructions at 
# https://github.com/AoHRuthless/PlayerLauncher/wiki/Config.yml
# PlayerLauncher can be downloaded at http://dev.bukkit.org/bukkit-plugins/playerlauncher/
# Have any issues or bugs with the plugin? Report them at the following link:
# https://github.com/AoHRuthless/PlayerLauncher/issues?state=open
#
# +---------------------------------------------------------------------------------------------+ #
#
Launch:
#
# Do you want launching to be enabled?
  Enabled: true
# 
# The prefix you want to use for most PlayerLauncher messages.
  Prefix: '&6[PlayerLauncher]'
#
# The message received when a player launches. You may use '&' color codes. Remember to enclose the
# message in '' (single quotation marks) or errors will be thrown.
  Message: '&dYou have been launched. Sayonara!'
#  
# You can customize different effects when a player launches themself. Sound effects are not 
# Case-Sensitive. You can enable fireworks or disable them as a true or false setting. Set sound 
# to blank to disable sound effects.
  Effects:
    Sound: Explode
    Fireworks: true
#  
# When a player tries to launch themself, what items do we want them to have? Set the amount
# to 0 to disable. The item MUST BE the item name, not an Item Id.
  Requirement:
    Amount: 1
    Item: diamond
#   
# Do we want to remove the required items after a player launches themself?
  Remove-Required-Items-After-Launch: true
  
# How many seconds passes between the time at which a player uses /l and the launch occurs?
  Delay: 5
#
# What is the strength of the launch? CAUTION: Advanced users only, as this can cause
# players to be kicked for flying, lag, client crashing, and more if the power is too high.
  Power: 8
#  
# What block can a player automatically launch off of? Launch pads are stored in launchpads.yml
  Launch-Pad: Wood_Plate
# 
# The following settings are related to explosions. You can enable / disable, set the amount of
# TNT required to explosive launch, and the power of the explosion. 4 is that of default TNT.
# The amount required does not affect the radius or power of the explosion in any way.
  Explosions:
    Enabled: true
    Amount: 5
    Power: 4
#
# Setting to true will notify all ops and players with PlayerLauncher.admin when an update for
# PlayerLauncher is available. Enabling this does not harm your server in any way, shape, or form
# and it's purpose is nothing but to allow updates for the plugin to be distributed quickly and
# easily. If you have any questions about this feature pm me (AoH_Ruthless) on BukkitDev.
  Update-Notifications: true
# +---------------------------------------------------------------------------------------------+ #
# Version 1.4.5
# You are done with configuration.    
